### ISSUE TITLE
"npm install" doesn't work for ember-cli-jsdoc

### ISSUE THREAD

**Issue by ewoody** [softlayer/ember-cli-jsdoc#19] opened 2016-03-10 15:28 UTC
Reproduce path - 
1. ember install ember-cli-jsdoc
2. delete node_modules
3. npm install

Expected
Since after step 1, "ember-cli-jsdoc": "1.3.1", is added in package.json, I expected the "npm install" should install ember-cli-jsdoc addon in a clean directory. It is normal for other ember addons, and it is useful for continuous integration build server.

Problem
after npm install on step 3, jsdoc is not installed correctly.

**Comment by SpikedKira** [comment] 2016-03-10 15:42
I think step 1 should be `npm install ember-cli-jsdoc --save-dev`

**Comment by notmessenger** [comment] 2016-03-10 16:31
@SpikedKira That way does not invoke the Ember CLI ecosystem, which you need for the installation of this addon, as it will then leverage the blueprint, so `ember install ember-cli-jsdoc` is correct.

@ewoody When you say that jsdoc is not installed correctly what are you seeing? Can you provide more details?  I just started seeing something weird the other day in a CircleCI environment and am curious of the characteristics you are seeing.

**Comment by ewoody** [comment] 2016-03-11 07:30
node_modules\ember-cli-jsdoc\node_modules\.bin folder doesn't have jsdoc and jsdoc.cmd at all.

**Comment by ewoody** [comment] 2016-03-11 08:53
- npm install ember-cli-jsdoc --save-dev  - doesn't work. the installed package doesn't have right content in PROJECT\node_modules\ember-cli-jsdoc\node_modules\.bin folder. Same problem.
- ember install doesn't work in our CI server, we got the npm cache error from ember install, 
  EPERM: operation not permitted, rename package.json.235057398 to package.json
- The information from other source, where they expect the npm install should work for this addon, for example, https://www.versioneye.com/nodejs/ember-cli-jsdoc/1.3.1

There is no problem of installation on my local PC, the problem is our CI server can't use "ember install" as a step to build project.

**Comment by notmessenger** [comment] 2016-03-19 17:36
**CAUSE**
- Version 5.0.0 of Node.js upgraded its npm dependency from 2.14.7 to 3.3.6 (see https://nodejs.org/en/blog/release/v5.0.0/)
- npm v3 handles dependency resolution in a different way than npm2 (see https://docs.npmjs.com/how-npm-works/npm3)
- The path construction of https://github.com/softlayer/ember-cli-jsdoc/blob/master/lib/commands/ember-cli-jsdoc.js#L10 does not correctly account for these differences in npm versions.

**FIX**
- Modify the path construction in https://github.com/softlayer/ember-cli-jsdoc/blob/master/lib/commands/ember-cli-jsdoc.js#L10 to accommodate npm versions 2 and 3

**Comment by notmessenger** [comment] 2016-03-19 17:43
@ewoody unrelated to what is the root cause of this issue, I'm curious about your comment in https://github.com/softlayer/ember-cli-jsdoc/issues/19#issuecomment-195263543 regarding your CI server not being able to use `ember install`.  Are you installing ember addons as part of your build process in your CI environment or was that only in an attempt to diagnose this issue?  Because if it is the former this is an unusual configuration, at least from my experience.

**Comment by notmessenger** [comment] 2016-03-19 22:28
https://github.com/softlayer/ember-cli-jsdoc/releases/tag/v1.3.2 has been released to address this issue.

**Comment by ewoody** [comment] 2016-03-21 08:35
binary files have not been copied in right location by npm install. that is - 

the files in PROJECT_FOLDER\node_modules\ember-cli-jsdoc\node_modules.bin

should be copied to

PROJECT_FOLDER\node_modules.bin

so that our CI server doesn't work still.

**Comment by notmessenger** [comment] 2016-03-21 10:59
@ewoody Which version of Node are you using on your CI server? Have you re-ran the build with no cache to ensure you are getting the latest version of this addon?

**Comment by ewoody** [comment] 2016-03-22 13:51
I have verified that the v1.3.2 works for me after I deleted entire PROJECT_FOLDER\node_modules and re-run npm install. 

Thank you for this fix.

**Comment by mrryanjohnston** [comment] 2016-09-23 22:53
This issue still exists with v1.4.0.

Steps to reproduce:
1. Create a new ember project `ember new foobar`
2. `cd foobar`
3. `ember install ember-cli-jsdoc`
4. `ember ember-cli-jsdoc`

```
$ ember ember-cli-jsdoc
/bin/sh: node_modules/.bin/jsdoc: No such file or directory

EMBER-CLI-JSDOC: ERRORs have occurred during documentation generation
```

I can confirm that https://github.com/softlayer/ember-cli-jsdoc/issues/19#issuecomment-199825535 does resolve the issue.

**Comment by notmessenger** [comment] 2016-09-25 04:14
I have been able to recreate the scenario outlined in https://github.com/softlayer/ember-cli-jsdoc/issues/19#issuecomment-249320765 including how to resolve it.

If when following the same steps instead of running Step 3: `ember install ember-cli-jsdoc` I run these two commands instead:
- `npm install ember-cli-jsdoc`
- `ember g ember-cli-jsdoc` (though not entirely necessary to troubleshoot this particular issue)

then the problem no longer occurs.

@mrryanjohnston I am going to reopen this issue and spend some time researching a few more items, which may possibly result in opening an issue with Ember CLI (depending on what some of my current thoughts to research turn up).  I will update this issue with appropriate links and information as they occur.  Thank you for reporting this behavior.

**Comment by notmessenger** [comment] 2016-09-25 20:13
Have found this that is sort of related behavior - http://stackoverflow.duapp.com/questions/37142438/npm-node-modules-bin-symlinks

**Comment by notmessenger** [comment] 2016-11-25 01:01
Believe this is resolved by https://github.com/softlayer/ember-cli-jsdoc/releases/tag/v1.4.1

**Closed as completed by notmessenger** 2016-11-25 01:01 UTC
Labels: bug
